export const AUTH_LOGIN_USER = 'AUTH_LOGIN_USER';
export const AUTH_LOGIN_USER_FAIL = 'AUTH_LOGIN_USER_FAIL';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_CREATE_USER = 'AUTH_CREATE_USER';
export const AUTH_CREATE_USER_FAIL = 'AUTH_CREATE_USER_FAIL';
export const AUTH_CREATE_USER_SUCCESS = 'AUTH_CREATE_USER_SUCCESS';
// Post types.
export const POST_FETCH_ALL = 'POST_FETCH_ALL';
export const POST_LIKE = 'POST_LIKE';
export const POST_DISLIKE = 'POST_DISLIKE';
export const POST_ADD_COMMENT = 'POST_ADD_COMMENT';
export const POST_SELECT_IMAGE = 'POST_SELECT_IMAGE';
export const POST_ADD = 'POST_ADD';
